// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAwFfRHyBllaP5xDU6MMazBhUd0ZSt34U',
    appId: '1:993601605339:web:85fb50d8395d862c1786fe',
    messagingSenderId: '993601605339',
    projectId: 'biblioteca-22429',
    authDomain: 'biblioteca-22429.firebaseapp.com',
    storageBucket: 'biblioteca-22429.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDqNCzYuVRgfGuqpECXjatO6eOWXYwbac',
    appId: '1:993601605339:android:5a382d41e113bd1f1786fe',
    messagingSenderId: '993601605339',
    projectId: 'biblioteca-22429',
    storageBucket: 'biblioteca-22429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUePVPR6Poh4GV_ZwL-iVhiOA5DXMH4HQ',
    appId: '1:993601605339:ios:b6379bcde864eca91786fe',
    messagingSenderId: '993601605339',
    projectId: 'biblioteca-22429',
    storageBucket: 'biblioteca-22429.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUePVPR6Poh4GV_ZwL-iVhiOA5DXMH4HQ',
    appId: '1:993601605339:ios:b6379bcde864eca91786fe',
    messagingSenderId: '993601605339',
    projectId: 'biblioteca-22429',
    storageBucket: 'biblioteca-22429.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAwFfRHyBllaP5xDU6MMazBhUd0ZSt34U',
    appId: '1:993601605339:web:66fce57783784af61786fe',
    messagingSenderId: '993601605339',
    projectId: 'biblioteca-22429',
    authDomain: 'biblioteca-22429.firebaseapp.com',
    storageBucket: 'biblioteca-22429.firebasestorage.app',
  );
}
